### ISSUE TITLE
Unable to pull/build 1903 servercore/nanoserver images

### ISSUE THREAD

**Issue by Justin-DynamicD** [microsoft/azure-pipelines-image-generation#1019]
**Describe the bug**
I have a simple pipeline configured that checks the tags list for nanoserver by doing a simple get-webrequest against "https://mcr.microsoft.com/v2/windows/nanoserver/tags/list".  It then grabs the latest 4 digit build (1903 currently) and uses that to perform  multi-stage docker build off that version (servercore first ... then copy everything into nanoserver when ready).

**Expected behavior**
during this stage of the azure-pipeline yaml, I expect servercore:1903 to download, the tag is passed to the docker file via the build-arg

```yaml
- task: Docker@2
  displayName: Build
  condition: succeeded()
  inputs:
    command: build
    arguments: --build-arg VERSIONNANO=$(versionNano)
    repository: $(dockerrepo)
    tags: |
      latest
      $(versionNano)
```

**Actual behavior**
"no matching manifest" is returned and no image downloads.  The pipeline is public, so feel free to look:

[public project ftw](https://dev.azure.com/jkingXell/Dockerize%20Windows/_build/results?buildId=37)

reminder the ARG is a default value in case nothing is passed.  removing the arguments from the task in the yaml will result in a successful build.

**Image impacted**
Build is attempted on `windows-2019`.  Builds earlier than 1903 work fine (1809 for example).  windows-2019 was chosen so invoke-webrequest can run without issue.
