### ISSUE TITLE
Rust (cargo, rustc) sometimes missing in Ubuntu 16.04 images

### ISSUE THREAD

**Issue by technosophos** [microsoft/azure-pipelines-image-generation#1024]
**Describe the bug**
About 25% of the time, my Azure Pipelines builds fail because the Rust toolchain cannot be found. The rest of the time, it works fine. Often, simply re-running the build will fix the issue.

My azure-pipelines.yml file is as follows:

```yaml
pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: |
    cargo version
    rustc --version
    cargo test
  displayName: 'Run unit tests'
```

**Expected behavior**
Azure Pipelines invocations should have the same tools available for every build.

**Actual behavior**
Builds fail ~25% of the time with the following error:
<img width="810" alt="Screen Shot 2019-06-18 at 14 52 23" src="https://user-images.githubusercontent.com/89193/59783115-a7c7cd00-927c-11e9-9f8b-f631cef4ce98.png">

**Image impacted**
ubuntu
