### ISSUE TITLE
ubuntu-16.04 Python 3.6, 3.7: Curses module failing

### ISSUE THREAD

**Issue by asottile** [microsoft/azure-pipelines-image-generation#1207]
**Describe the bug**

It appears the pythons compiled for the hosted ubuntu agents were compiled with missing support for curses.

A normal python should be able to run this script for example:

```python
import curses

def c_main(stdscr):
    stdscr.get_wch()

def main():
    curses.wrapper(c_main)

if __name__ == '__main__':
    exit(main())
```

Here's the output from vanilla python3 on ubuntu xenial:

```console
root@31d72f5ec1cb:/# echo x | python3 t.py
root@31d72f5ec1cb:/# 
```

_**The usual fix for this is to ensure `libncursesw5-dev` is installed while building python**_

**Expected behavior**

I expect the pythons on azure pipelines to be able to run curses applications that utilize `get_wch`, however they cannot.

**Actual behavior**

[example build](https://asottile.visualstudio.com/asottile/_build/results?buildId=1249)

```
===============================================================================
Traceback (most recent call last):
  File "/home/vsts/work/1/s/babi.py", line 400, in <module>
    exit(main())
  File "/home/vsts/work/1/s/babi.py", line 395, in main
    curses.wrapper(c_main, args)
  File "/opt/hostedtoolcache/Python/3.6.9/x64/lib/python3.6/curses/__init__.py",
 line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/vsts/work/1/s/babi.py", line 286, in c_main
    return _color_test(stdscr)
  File "/home/vsts/work/1/s/babi.py", line 186, in _color_test
    stdscr.get_wch()
AttributeError: '_curses.window' object has no attribute 'get_wch'
```

**Image impacted**
ubuntu

#996 is a related bug, but was for `_sqlite3`

**Comment by asottile** [comment]
I'm working around this by installing properly built pythons from [deadsnakes](https://github.com/deadsnakes) -- however this adds ~80s to each run which is pretty unfortunate

Here's some approximate code for that:

```yaml
  - bash: |
      sudo add-apt-repository ppa:deadsnakes
      sudo apt-get update
      sudo apt-get install -y --no-install-recommends $(python)
    displayName: install deadsnakes python
  - bash: |
      curl https://asottile.github.io/get-virtualenv.py | $(python) - /tmp/venv
      /tmp/venv/bin/pip install tox
      echo '##vso[task.prependpath]/tmp/venv/bin'
    displayName: install tox
```

**Comment by brcrista** [comment]
Hm, we do install `libncursesw5-dev` when building Python.  I wonder if it's having an issue finding the `.so` file at run time.  I'll look into it some more.

**Comment by brcrista** [comment]
Thanks for providing a workaround, by the way.

I actually get a different error when I try to repro:

```
    cbreak()
_curses.error: cbreak() returned ERR

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".azure-pipelines/scripts/test_curses.py", line 10, in <module>
    exit(main())
  File ".azure-pipelines/scripts/test_curses.py", line 7, in main
    curses.wrapper(c_main)
  File "/opt/hostedtoolcache/Python/3.6.9/x64/lib/python3.6/curses/__init__.py", line 100, in wrapper
    nocbreak()
```

Am I missing something in my setup?  Here's the YAML I'm using:

```yml
pool:
  vmImage: ubuntu-16.04

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'
  displayName: Use Python 3.6

- script: |
    export TERM=linux
    export TERMINFO=/etc/terminfo
    python .azure-pipelines/scripts/test_curses.py
  displayName: Run curses script
```

**Comment by asottile** [comment]
that'll happen if you don't have a controlling tty attached, try `echo x | python .azure-pipelines/scripts/test_curses.py` instead

**Comment by brcrista** [comment]
Hm, no luck.  I was running without the `TERM` and `TERMINFO` environment variables before, but I was getting `_curses.error: setupterm: could not find terminal`.

I see your code in `babi.py` has some additional curses setup, so maybe that's why.

I'm not too familiar with `curses`.  In `_sqlite3` issue you referenced, the `.so` was missing and the call to `import sqlite3` would fail right away.  It looks like we are getting past that, so I wonder if there is some version mismatch between what we build with and what is present at run time.

**Comment by asottile** [comment]
hang on, let me get you a full reproduction then :thinking:

**Comment by asottile** [comment]
Here's a full reproduction:

### t.py

```python
import curses

def c_main(stdscr):
    stdscr.get_wch()

def main():
    curses.wrapper(c_main)

if __name__ == '__main__':
    exit(main())
```

### azure-pipelines.yml

```yaml
trigger:
  branches:
    include: [master, test-me-*]
  tags:
    include: ['*']

jobs:

- job: default
  pool:
    vmImage: ubuntu-16.04
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
  - bash: ldd $(python3.6 -c 'import _curses; print(_curses.__file__)')
    displayName: ldd
  - bash: |
        tmux -u -L deadbeef new-session -d -x 80 -y 24 "bash -c 'python3 t.py; sleep infinity'"
        sleep 1
        tmux -u -L deadbeef capture-pane -t 0 -p > buffer
        grep -C999 Error buffer && exit 1
        echo 'success!'
    displayName: run demo

- job: workaround
  pool:
    vmImage: ubuntu-16.04
  steps:
  - bash: |
      sudo add-apt-repository ppa:deadsnakes
      sudo apt-get update
      sudo apt-get install -y --no-install-recommends python3.6
    displayName: install deadsnakes python
  - bash: ldd $(python3.6 -c 'import _curses; print(_curses.__file__)')
    displayName: ldd
  - bash: |
        tmux -u -L deadbeef new-session -d -x 80 -y 24 "bash -c 'python3 t.py; sleep infinity'"
        sleep 1
        tmux -u -L deadbeef capture-pane -t 0 -p > buffer
        grep -C999 Error buffer && exit 1
        echo 'success!'
```

(note: I used `tmux` as it's an easy way to get a pty without having to do the whole pipes dance, seems AP doesn't run with a `pty` anyway (that's fine!))

The relevant outputs:

### ldd

(broken, standard azure pipelines)
```
	linux-vdso.so.1 =>  (0x00007ffe95572000)
	libncurses.so.5 => /lib/x86_64-linux-gnu/libncurses.so.5 (0x00007f646b4bb000)
	libtinfo.so.5 => /lib/x86_64-linux-gnu/libtinfo.so.5 (0x00007f646b292000)
	libpython3.6m.so.1.0 => /opt/hostedtoolcache/Python/3.6.9/x64/lib/libpython3.6m.so.1.0 (0x00007f646ad26000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f646ab09000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f646a73f000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f646a53b000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f646a338000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f646a02f000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f646b8f1000)
```

(correct, deadsnakes python)

```
	linux-vdso.so.1 =>  (0x00007fffe91af000)
	libncursesw.so.5 => /lib/x86_64-linux-gnu/libncursesw.so.5 (0x00007f950f51c000)
	libtinfo.so.5 => /lib/x86_64-linux-gnu/libtinfo.so.5 (0x00007f950f2f3000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f950f0d6000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f950ed0c000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f950eb08000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f950f95f000)
```

important difference, the azure pipelines python is incorrectly linked against `libncurses.so.5` it should be linked against `libncurses*w*.so.5`


### demo job

(failing, azure pipelines python)

```
[command]/bin/bash --noprofile --norc /home/vsts/work/_temp/6eb22c42-8daf-4f1c-b0c0-93e540ec2f42.sh
Traceback (most recent call last):
  File "t.py", line 10, in <module>
    exit(main())
  File "t.py", line 7, in main
    curses.wrapper(c_main)
  File "/opt/hostedtoolcache/Python/3.6.9/x64/lib/python3.6/curses/__init__.py",
 line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "t.py", line 4, in c_main
    stdscr.get_wch()
AttributeError: '_curses.window' object has no attribute 'get_wch'












##[error]Bash exited with code '1'.
```

(passing, deadsnakes python)

```
[command]/bin/bash --noprofile --norc /home/vsts/work/_temp/ef000fab-3363-42aa-8182-7355678e9ecf.sh
success!
```

Here's the build result: https://asottile.visualstudio.com/asottile/_build/results?buildId=1261
