### ISSUE TITLE
`windows-2019` is missing MSBuild 16.3.0

### ISSUE THREAD

**Issue by haavamoa** [microsoft/azure-pipelines-image-generation#1256]
**Describe the bug**
Running a Dotnet Core Test with 3.0.100 on `windows-2019` throws an error `Version 3.0.100 of the .NET Core SDK requires at least version 16.3.0 of MSBuild`
[Link to build](https://dev.azure.com/dipscloud-public/Public%20Pipelines/_build/results?buildId=73&view=logs&j=275f1d19-1bd8-5591-b06b-07d489ea915a)

**Expected behavior**
That tests are running on dotnet core 3.0.

**Actual behavior**
Tests are not running and the build says that we are missing MSBuild 16.3.0

1. Create a test project 
2. Use task to add dotnet core 3.0
3. Try running the tests on a windows-2019 image
4. Observe the error

**Comment by virzak** [comment]
I had the same issue. Hopefully it is fixed soon.

In the meantime, the workaround is to use 3.0.100-rc1-014190 which works with the `windows-2019`

**Comment by Mgamerz** [comment]
Noticed the same issue. Watched the keynote and stuff and want to try this out! I just ported most of my app to .net core after some finagling.

**Comment by kaylangan** [comment]
Thanks for the report! We're working on a fix and will roll out a new deployment.

**Comment by haavamoa** [comment]
I made it work by making sure that my test project was running on `Dotnet Core App 3.0`. I was targeting the wrong one (`2.1`).
The error still occurs when try to use the `Nuget restore` task and targeting my whole solution file though.

**Comment by glennawatson** [comment]
It also is an issue with multi-targetting projects. Such as those using MSBuild.Sdk.Extras with .net core 3 RTM.

**Comment by rmarinho** [comment]
@kaylangan how do we get notifications for when you deploy update. And the ring it is ?

**Comment by dkmiller** [comment]
@kaylangan this issue is also affecting the hosted Ubuntu agents. Will the incoming fix include them, or should I file a separate issue for those?

**Comment by virzak** [comment]
@kaylangan Is there a process where major releases are planned for? Other Microsoft library vendors aim their releases to coincide with the major release dates. However for .net core 3.0 release, like with .NET Framework 4.8 earlier, upgrading software on the build machines seems like an afterthought.

**Comment by joaopgrassi** [comment]
> @kaylangan Is there a process where major releases are planned for? Other Microsoft library vendors aim their releases to coincide with the major release dates. However for .net core 3.0 release, like with .NET Framework 4.8 earlier, upgrading software on the build machines seems like an afterthought.

Yeah, it seems quite strange to me as well. I mean, we all knew .NET Core 3.0 was coming so.. I wonder why the images didn't get updated at the same time as well?

**Comment by glennawatson** [comment]
I noticed when they deploy images in the past it tends to take time to propogate to all their hosts.  So could be that.

**Comment by dovic95** [comment]
> I had the same issue. Hopefully it is fixed soon.
> 
> In the meantime, the workaround is to use 3.0.100-rc1-014190 which works with the `windows-2019`

I tried your workaround but I get this error during the Nuget Restore task:  `error : Unable to locate the .NET Core SDK. Check that it is installed and that the version specified in global.json (if any) matches the installed version`

Here is the content of my global.json file 
```json
{
    "sdk": {
      "version": "3.0.100"
    },
    "msbuild-sdks": {
      "MSBuild.Sdk.Extras": "2.0.24"
    }
  }
```

And here is my build configuration

```yaml
- task: UseDotNet@2
  displayName: 'Install .net core 3.0'
  inputs:
    packageType: 'sdk'
    version: '3.0.100-rc1-014190'
    includePreviewVersions: true
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: 5.3.0
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: 'MyApp.sln'
    feedsToUse: 'config'
    nugetConfigPath: 'NuGet.config'
```

I don't understand why the .Net Core SDK could not be found

**Comment by glennawatson** [comment]
Likely looking for the RTM version I suspect, I would try setting your sdk version to `3.0.100-rc1-014190`. Only required until MSBuild 16.3 is deployed.

**Comment by virzak** [comment]
@dovic95 

That's because your `global.json` doesn't have the same version as the SDK.

Either change it to alpha (but then you need alpha on your machine) or delete `global.json` from repo and add a task to create config.json right after you get the SDK.

```
- task: DotNetCoreCLI@2
  displayName: 'dotnet globaljson'
  inputs:
    command: custom
    custom: new
    arguments: 'globaljson --sdk-version 3.0.100-rc1-014190'
```
