### ISSUE TITLE
[Enhancement] Update Visual Studio for Mac for macos-10.14

### ISSUE THREAD

**Issue by haavamoa** [microsoft/azure-pipelines-image-generation#1296]
**Describe the bug**
I have just updated my Xamarin.Forms shared project to use C# 8 and nullable feature. When I try to build it in my CI pipeline in Azure Devops i keep getting;
`error CS1617: Invalid option '8.0' for /langversion. Use '/langversion:?' to list supported values.`

I am downloading and selecting Dotnet Core 3.0 from my `global.json` file in my repository. 

I can see in the spec that we are not on the latest visual studio for Mac. Is that the reason behind this issue? If so, when can we expect an upgrade? 

**Expected behavior**
Run fine with C# 8 and nullable. 

**Actual behavior**
Fails to find the language.

1. Create a net standard project that target C# 8.
2. Build it in azure pipeline with `macOS-10.14`

**Comment by maxim-lobanov** [comment]
@haavamoa, Currently, VS4Mac 8.3.0.1805 is installed on `macOS-10.14`. VS4Mac 8.3.1 will be shipped in a few days.
The both versions support C# 8 so please make sure that you setup correct settings. I was able to build Xamarin.Forms app with C# 8 using the following settings:
1) UseDotNet 3.0.100:
```
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    useGlobalJson: true
```
2) Mono version 6.4 ([Configuration link](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=designer#mono))
```
- bash: |
    SYMLINK=6_4_0
    MONOPREFIX=/Library/Frameworks/Mono.framework/Versions/$SYMLINK
    echo "##vso[task.setvariable variable=DYLD_FALLBACK_LIBRARY_PATH;]$MONOPREFIX/lib:/lib:/usr/lib:$DYLD_LIBRARY_FALLBACK_PATH"
    echo "##vso[task.setvariable variable=PKG_CONFIG_PATH;]$MONOPREFIX/lib/pkgconfig:$MONOPREFIX/share/pkgconfig:$PKG_CONFIG_PATH"
    echo "##vso[task.setvariable variable=PATH;]$MONOPREFIX/bin:$PATH"
```

**Comment by haavamoa** [comment]
> @haavamoa, Currently, VS4Mac 8.3.0.1805 is installed on `macOS-10.14`. VS4Mac 8.3.1 will be shipped in a few days.
> The both versions support C# 8 so please make sure that you setup correct settings. I was able to build Xamarin.Forms app with C# 8 using the following settings:
> 
> 1. UseDotNet 3.0.100:
> 
> ```
> - task: UseDotNet@2
>   inputs:
>     packageType: 'sdk'
>     useGlobalJson: true
> ```
> 
> 1. Mono version 6.4 ([Configuration link](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=designer#mono))
> 
> ```
> - bash: |
>     SYMLINK=6_4_0
>     MONOPREFIX=/Library/Frameworks/Mono.framework/Versions/$SYMLINK
>     echo "##vso[task.setvariable variable=DYLD_FALLBACK_LIBRARY_PATH;]$MONOPREFIX/lib:/lib:/usr/lib:$DYLD_LIBRARY_FALLBACK_PATH"
>     echo "##vso[task.setvariable variable=PKG_CONFIG_PATH;]$MONOPREFIX/lib/pkgconfig:$MONOPREFIX/share/pkgconfig:$PKG_CONFIG_PATH"
>     echo "##vso[task.setvariable variable=PATH;]$MONOPREFIX/bin:$PATH"
> ```

@maxim-lobanov, thank you so much for the reply. I will try this out first thing in the morning. Looking forward to the update for VS4Mac. :+1:

**Comment by haavamoa** [comment]
@maxim-lobanov :
 I tried to do the same as you do, but now I get linker errors:

```

**Comment by maxim-lobanov** [comment]
Sorry, didn't face to same issues and can't reproduce without demo project.
What configuration do you use locally?


A one more idea from my side: please make sure that current Xcode, Mono, Xamarin.iOS are compatible with each other.

1) UseDotNet 3.0.100:
```
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    useGlobalJson: true
```
2) Mono version 6.4
```
- bash: |
    SYMLINK=6_4_0
    MONOPREFIX=/Library/Frameworks/Mono.framework/Versions/$SYMLINK
    echo "##vso[task.setvariable variable=DYLD_FALLBACK_LIBRARY_PATH;]$MONOPREFIX/lib:/lib:/usr/lib:$DYLD_LIBRARY_FALLBACK_PATH"
    echo "##vso[task.setvariable variable=PKG_CONFIG_PATH;]$MONOPREFIX/lib/pkgconfig:$MONOPREFIX/share/pkgconfig:$PKG_CONFIG_PATH"
    echo "##vso[task.setvariable variable=PATH;]$MONOPREFIX/bin:$PATH"
```

3) Xcode 11.1
```
echo '##vso[task.setvariable variable=MD_APPLE_SDK_ROOT;]'/Applications/Xcode_11.1.app
sudo xcode-select --switch /Applications/Xcode_11.1.app/Contents/Developer"
```

4) Xamarin.iOS 13.2
```
sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh 6_4_0
```

**Comment by haavamoa** [comment]
I understand, I will have to create a minimal reproducible repository and create a new pipeline that is public to show it to you. 

I will try to set the rest of the versions before I do that, thank you so much! 👍

**Comment by haavamoa** [comment]
That solved my issue @maxim-lobanov .

Is there any plans for this to be included in the current images? Feels like a lot of overhead to run dotnet core 3 Xamarin.

**Comment by maxim-lobanov** [comment]
The reason for that overhead work is outdated default versions of software. I mean, we install Mono 6.4 on image but keep 5.12 as default for some .NET Core compatibility issues. So need to switch it during the build.

macOS 10.15 (Catalina) will deprecate a lot of incompatible software and improve this experience significantly (default version will be latest version for Xcode, Mono, Xamarin and .NET Core).
However, I don't have any ETA for Catalina at this moment.

**Comment by Ryan-Palmer** [comment]
Hello, I am trying to get a Xamarin build going which uses .Net Core 3 and I am so close but have fallen at the last hurdle and now I am stuck. I'm using the 10.14 macOS image host.

Firstly I had to update Nuget Restore in order to clone .Net Core 3 packages.

This required me to update Mono to get a newer xbuild, so I used Boots to install the closest version to the one on my machine.

I also used Boots to install the same Xamarin.iOS version I have on my local machine.

I added a Bash script to point at the new Mono.

This left me with an error saying that I needed a newer iOS SDK version, and to achieve this I needed at least Xcode 11.2.

I have added another Bash step to switch to XCode 11.2, and it runs ok, however I am left with this error:

`/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.Common.targets(673,3): error : Could not find a valid Xcode app bundle at ' /Applications/Xcode_11.2.app'. Please update your Apple SDK location in Visual Studio's preferences (Project > SDK Locations > Apple > Apple SDK).
`
The weird thing is if I list everything in the /Applications folder using the Bash script, that version of XCode is clearly installed and available.

Here is my YAML:

```
steps:
- task: UseDotNet@2
  displayName: 'Install .Net Core 3.0.x'
  inputs:
    version: 3.0.x

- task: InstallAppleCertificate@2
  displayName: 'Install an Apple certificate'
  inputs:
    certSecureFile: 'db642a53-5631-4e9e-8c72-54f1dd7afb9f'
    certPwd: '$(P12password)'
    signingIdentity: com.myidentity.app

- task: InstallAppleProvisioningProfile@1
  displayName: 'Install an Apple provisioning profile'
  inputs:
    provProfileSecureFile: '70cdb58c-b3e8-453e-b563-53ce7bb19d8b'

- task: pjcollins.azp-utilities-boots.boots.Boots@1
  displayName: 'Update Mono'
  inputs:
    uri: 'https://download.mono-project.com/archive/6.6.0/macos-10-universal/MonoFramework-MDK-6.6.0.156.macos10.xamarin.universal.pkg'

- task: pjcollins.azp-utilities-boots.boots.Boots@1
  displayName: 'Update Xamarin.iOS'
  inputs:
    uri: 'https://dl.xamarin.com/MonoTouch/Mac/xamarin.ios-13.8.2.2.pkg'

- bash: |
   SYMLINK=6_6_0_156
   MONOPREFIX=/Library/Frameworks/Mono.framework/Versions/$SYMLINK
   echo "##vso[task.setvariable variable=DYLD_FALLBACK_LIBRARY_PATH;]$MONOPREFIX/lib:/lib:/usr/lib:$DYLD_LIBRARY_FALLBACK_PATH"
   echo "##vso[task.setvariable variable=PKG_CONFIG_PATH;]$MONOPREFIX/lib/pkgconfig:$MONOPREFIX/share/pkgconfig:$PKG_CONFIG_PATH"
   echo "##vso[task.setvariable variable=PATH;]$MONOPREFIX/bin:$PATH"
  displayName: 'Select Mono version'

- bash: |
   echo "##vso[task.setvariable variable=MD_APPLE_SDK_ROOT;]" /Applications/Xcode_11.2.app
   
   sudo xcode-select --switch /Applications/Xcode_11.2.app/Contents/Developer
   
   echo "Xcode version: "
   xcodebuild -version
   
   echo "Installed applications: "
   for entry in /Applications/*
   do
     echo "$entry"
   done
  displayName: 'Select XCode Version'

- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 5.4.0'
  inputs:
    versionSpec: 5.4.0

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: '$(Parameters.solution)'

- task: XamariniOS@2
  displayName: 'Build Xamarin.iOS solution **/*.sln'
  inputs:
    solutionFile: '$(Parameters.solution)'
    configuration: '$(BuildConfiguration)'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**/*.ipa'
    TargetFolder: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()

```
