### ISSUE TITLE
azure-devops cli extension is not installed on Ubuntu 16.04 hosted agent

### ISSUE THREAD

**Issue by olandese** [microsoft/azure-pipelines-image-generation#1314]
According to the readme (https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/linux/Ubuntu1604-README.md) the Azure CLI DevOps extension should be installed Azure CLI (azure-devops 0.12.0).
Running pipeline on the hosted :

```
trigger:
- master

pool: "Hosted Ubuntu 1604"

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'XXXXX'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az --version'
```
This is the output:

azure-cli                         2.0.74

command-modules-nspkg              2.0.3
core                              2.0.74
nspkg                              3.0.4
telemetry                          1.0.3

Python location '/opt/az/bin/python3'
Extensions directory '/home/vsts/work/_temp/.azclitask/cliextensions'

It seems that the azure-devops cli extensions is not installed on the Ubuntu 16.04 hosted agent
