### ISSUE TITLE
Can't use non-default XCode version on macOS hosted agent

### ISSUE THREAD

**Issue by Ryan-Palmer** [microsoft/azure-pipelines-image-generation#1441]
Hello, sorry if this isn't the right repo to post this issue. I am trying to get a Xamarin build going which uses .Net Core 3 / .Net Standard 2.1 libraries and I am so close but have fallen at the last hurdle and now I am stuck. I'm using the 10.14 macOS image host.

After installing .Net Core 3 I had to update Nuget Restore in order to clone .Net Core 3 packages.

This required me to update Mono to get a newer xbuild, so I used Boots to install the closest version to the one on my machine.

I added a Bash script to point at the new Mono.

This allowed the pipeline to reach the solution build step, which failed with
` MTOUCH : error MT4109: Failed to compile the generated registrar code.`

I read that this is due to an old version of Xamarin.iOS being installed, so I added another Boots step to update that to the same version as my local machine.

This left me with a new error when building my solution:
`MTOUCH : error MT0091: This version of Xamarin.iOS requires the iOS 13.2 SDK (shipped with Xcode 11.2)`

I added another Bash step to switch to XCode 11.2 and it runs ok with the expected output printed, however I am now left with this error when I try to build the solution:

`/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.Common.targets(673,3): error : Could not find a valid Xcode app bundle at ' /Applications/Xcode_11.2.app'. Please update your Apple SDK location in Visual Studio's preferences (Project > SDK Locations > Apple > Apple SDK).
`

The weird thing is if I list everything in the /Applications folder using the Bash script, that version of XCode is clearly installed and available.

Here is my YAML:

```
steps:
- task: UseDotNet@2
  displayName: 'Install .Net Core 3.0.x'
  inputs:
    version: 3.0.x

- task: InstallAppleCertificate@2
  displayName: 'Install an Apple certificate'
  inputs:
    certSecureFile: 'db642a53-5631-4e9e-8c72-54f1dd7afb9f'
    certPwd: '$(P12password)'
    signingIdentity: com.myidentity.app

- task: InstallAppleProvisioningProfile@1
  displayName: 'Install an Apple provisioning profile'
  inputs:
    provProfileSecureFile: '70cdb58c-b3e8-453e-b563-53ce7bb19d8b'

- task: pjcollins.azp-utilities-boots.boots.Boots@1
  displayName: 'Update Mono'
  inputs:
    uri: 'https://download.mono-project.com/archive/6.6.0/macos-10-universal/MonoFramework-MDK-6.6.0.156.macos10.xamarin.universal.pkg'

- task: pjcollins.azp-utilities-boots.boots.Boots@1
  displayName: 'Update Xamarin.iOS'
  inputs:
    uri: 'https://dl.xamarin.com/MonoTouch/Mac/xamarin.ios-13.8.2.2.pkg'

- bash: |
   SYMLINK=6_6_0_156
   MONOPREFIX=/Library/Frameworks/Mono.framework/Versions/$SYMLINK
   echo "##vso[task.setvariable variable=DYLD_FALLBACK_LIBRARY_PATH;]$MONOPREFIX/lib:/lib:/usr/lib:$DYLD_LIBRARY_FALLBACK_PATH"
   echo "##vso[task.setvariable variable=PKG_CONFIG_PATH;]$MONOPREFIX/lib/pkgconfig:$MONOPREFIX/share/pkgconfig:$PKG_CONFIG_PATH"
   echo "##vso[task.setvariable variable=PATH;]$MONOPREFIX/bin:$PATH"
  displayName: 'Select Mono version'

- bash: |
   echo "##vso[task.setvariable variable=MD_APPLE_SDK_ROOT;]" /Applications/Xcode_11.2.app
   
   sudo xcode-select --switch /Applications/Xcode_11.2.app/Contents/Developer
   
   echo "Xcode version: "
   xcodebuild -version
   
   echo "Installed applications: "
   for entry in /Applications/*
   do
     echo "$entry"
   done
  displayName: 'Select XCode Version'

- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 5.4.0'
  inputs:
    versionSpec: 5.4.0

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: '$(Parameters.solution)'

- task: XamariniOS@2
  displayName: 'Build Xamarin.iOS solution **/*.sln'
  inputs:
    solutionFile: '$(Parameters.solution)'
    configuration: '$(BuildConfiguration)'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**/*.ipa'
    TargetFolder: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()

```
