### ISSUE TITLE
windows-latest / windows-2019 image states it has .NET Core SDK 3.1, but it does not

### ISSUE THREAD

**Issue by IanKemp** [microsoft/azure-pipelines-image-generation#1444]
https://github.com/microsoft/azure-pipelines-image-generation/blob/releases/vs2019/20191204/images/win/Vs2019-Server2019-Readme.md#net-core claims it includes SDK "3.1.100 C:\Program Files\dotnet\sdk\3.1.100", but attempting to build a .NET Core 3.1 project using that image fails with a message similar to the following because 3.1 is not actually installed:

`The current .NET SDK does not support targeting .NET Core 3.1.  Either target .NET Core 3.0 or lower, or use a version of the .NET SDK that supports .NET Core 3.1.`

In order to get a 3.1 project to build successfully, you have to manually install the 3.1 SDK with the `UseDotNet` task:

```yaml
- task: UseDotNet@2
  displayName: 'Get .NET Core 3.1 SDK'
  inputs:
    packageType: 'sdk'
    version: '3.1.x'
```

xref: #1435, #1438
