### ISSUE TITLE
Our python builds stopped working again

### ISSUE THREAD

**Issue by StingyJack** [microsoft/azure-pipelines-image-generation#1467]
The same build def and commit that worked last week do not work today. 

I have a build task to use the version of python needed (3.6.9), but that is apparently a fools task...

```
Version spec 3.6.9 for architecture x64 did not match any version in Agent.ToolsDirectory.
Versions in /opt/hostedtoolcache:
2.7.17 (x64)
3.5.9 (x64)
3.6.10 (x64)
3.7.6 (x64)
3.8.1 (x64)
If this is a Microsoft-hosted agent, check that this image supports side-by-side versions of Python at https://aka.ms/hosted-agent-software.
If this is a self-hosted agent, see how to configure side-by-side Python versions at https://go.microsoft.com/fwlink/?linkid=871498.
```

If you are really trying to improve in the area of builds and software maintenance, this is the place to start. Solve the problem in front of us first.

**Comment by vmapetr** [comment]
Hi @StingyJack! 

Thank you for reporting the issue. During recent image rollout we have updated Hostedtoolcache Python version from `3.6.9` to `3.6.10`.
Please check the documentation to find new updates:
Ubuntu 18.04 - https://github.com/actions/virtual-environments/blob/releases/ubuntu18/20200113/images/linux/Ubuntu1804-README.md
Ubuntu 16.04 - https://github.com/actions/virtual-environments/blob/releases/ubuntu16/20200113/images/linux/Ubuntu1604-README.md

To avoid `use Python version` task failures, you should use task without specified build version, e.g. `3.6` instead of `3.6.9`.

Example:
**VSTS - UsePythonVersion:**
```
  - task: UsePythonVersion@0
    displayName: 'Use Python $(VERSION)'
    inputs:
      versionSpec: '3.6'
      architecture: 'x64'
```
**GitHub - setup-python:**
```
- uses: actions/setup-python@v1
  with:
    python-version: '3.6' 
    architecture: 'x64'
```

With this approach currently installed build version will be used:

```
Found tool in cache: Python 3.6.10 x64
Prepending PATH environment variable with directory: /opt/hostedtoolcache/Python/3.6.10/x64
Prepending PATH environment variable with directory: /opt/hostedtoolcache/Python/3.6.10/x64/bin
```
