### ISSUE TITLE
windows-2019: cygheap base mismatch detected (git / bash)

### ISSUE THREAD

**Issue by asottile** [microsoft/azure-pipelines-image-generation#1468]
**Describe the bug**
Invoking `git` with a bash script as a hook results in `fatal error - cygheap base mismatch detected` -- it's possible this affects other invocations of bash scripts but I have not experimented with them

**Expected behavior**
It should succeed, it works on my windows VM and previously worked in azure pipelines

**Actual behavior**

Here is a minimal `azure-pipelines.yml`:

```yaml
trigger:
  branches:
    include: [master, test-me-*]
  tags:
    include: ['*']

jobs:
- job: demo
  pool:
    vmImage: windows-2019
  steps:
  - bash: |
      set -euxo pipefail
      git init x
      cd x
      echo -e '#!/usr/bin/env bash\necho hi\n' > .git/hooks/pre-commit
      chmod +x .git/hooks/pre-commit
      export GIT_AUTHOR_NAME='Anthony Sottile'
      export GIT_COMMITTER_NAME='Anthony Sottile'
      export GIT_AUTHOR_EMAIL=asottile@example.com
      export GIT_COMMITTER_EMAIL=asottile@example.com
      git commit --allow-empty -m "hello world"
```

This results in the following output from the `bash` step:

```
Starting: Bash
==============================================================================
Task         : Bash
Description  : Run a Bash script on macOS, Linux, or Windows
Version      : 3.159.3
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/bash
==============================================================================
Generating script.
"C:\Program Files\Git\usr\bin\bash.exe" --noprofile --norc -c pwd
/d/a/_temp

========================== Starting Command Output ===========================
"C:\Program Files\Git\usr\bin\bash.exe" --noprofile --norc /d/a/_temp/359ea791-1e08-4e06-a8eb-a68d6aefca31.sh
+ git init x
Initialized empty Git repository in d:/a/1/s/x/.git/
+ cd x
+ echo -e '#!/usr/bin/env bash\necho hi\n'
+ chmod +x .git/hooks/pre-commit
+ export 'GIT_AUTHOR_NAME=Anthony Sottile'
+ GIT_AUTHOR_NAME='Anthony Sottile'
+ export 'GIT_COMMITTER_NAME=Anthony Sottile'
+ GIT_COMMITTER_NAME='Anthony Sottile'
+ export GIT_AUTHOR_EMAIL=asottile@example.com
+ GIT_AUTHOR_EMAIL=asottile@example.com
+ export GIT_COMMITTER_EMAIL=asottile@example.com
+ GIT_COMMITTER_EMAIL=asottile@example.com
+ git commit --allow-empty -m 'hello world'
      0 [main] bash (1428) C:\Program Files\Git\usr\bin\bash.exe: *** fatal error - cygheap base mismatch detected - 0x180331408/0x180317408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.

##[error]Bash exited with code '1'.
```

**Image impacted**
windows-2019

here is the agent information:

```
Starting: Initialize job
Agent name: 'Hosted Agent'
Agent machine name: 'fv-az130'
Current agent version: '2.164.3'
Current image version: '20200113.1'
Agent running as: 'VssAdministrator'
Prepare build directory.
Set build variables.
Download all required tasks.
Downloading task: Bash (3.159.3)
Plugin: 'Test Result Parser plugin' is running in background.
Plugin: 'Test File Publisher plugin' is running in background.
Start tracking orphan processes.
Finishing: Initialize job
```
