### ISSUE TITLE
Add Inno Setup to Visual Studio 2017 Images

### ISSUE THREAD

**Issue by nick-thompson** [Microsoft/azure-pipelines-image-generation#261]
A free, popular tool for creating installers for Windows applications.
http://www.jrsoftware.org/isinfo.php

**Comment by bryanmacfarlane** [comment]
@chrisrpatterson - I don't believe we're going to be adding (and supporting) software packages like this.

Your available options are to pull JIT (that agent runs as administrator).  You can even create a tool installer task and add it to the marketplace.

Run a private agent on an azure VM.

**Comment by nick-thompson** [comment]
Thanks @bryanmacfarlane. So I've been playing with this for the better part of the past week, I don't mind installing it myself on a hosted agent (it's pretty simple with a `curl` and executing the installer with `/silent`), but the agent hangs currently because it's waiting for permission.

If I can run the `vs2017-win2016` agent with administrator privileges so as to avoid that permission prompt then I imagine the installation will be plenty easy (on a local Win10 installation I've been able to curl & install and everything works as expected after permission is given). I don't quite understand what you mean by "pull JIT" though? This is my config, how would I modify it to pull JIT?

```
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: MSBuild@1
    inputs:
      solution: 'projects/**/*.sln'
      platform: 'x64'
      configuration: 'release'
      clean: true
  - task: ShellScript@2
    inputs:
      scriptPath: ./scripts/azure-build_Windows.sh
```

(My `azure-build_Windows.sh` script is a bash script that curls and tries to install InnoSetup, that's where my build hangs currently)

And my understanding with the tool installers was that this was a preview feature that, currently, seems unavailable to me?
