### ISSUE TITLE
Python: Add PyPy3 6.0.0 (or latest) (Windows)

### ISSUE THREAD

**Issue by DavidStaheli** [Microsoft/azure-pipelines-image-generation#432]
Python: Add PyPy3 6.0.0 (or latest) (macOS, Windows)

**Comment by brcrista** [comment]
done

Use like

```yml
- task: UsePythonVersion@0
  displayName: Use PyPy2
  inputs:
    versionSpec: pypy2

- task: UsePythonVersion@0
  displayName: Use PyPy3
  inputs:
    versionSpec: pypy3
```
