### ISSUE TITLE
Scripting: Add/update to MSYS2 (latest) (Windows)

### ISSUE THREAD

**Issue by davidstaheli** [microsoft/azure-pipelines-image-generation#440]
This issue was created after a brief, cursory scan that found this missing.
Add/update to MSYS2 (latest) (Windows)

**Comment by berryzplus** [comment]
i wrote 2step below in `azure-pipelines.yml`, then i can build my cmake project written in C++.

```
  steps:
  - script: cinst msys2 --params "/InstallDir=C:/msys64" --no-progress
    displayName: install msys2

  - script: C:\msys64\usr\bin\bash --login -c "pacman -S --noconfirm mingw-w64-x86_64-gcc mingw-w64-x86_64-ninja mingw-w64-x86_64-cmake"
    displayName: install MinGW-w64-gcc, ninja, cmake
```

but these steps take almost 7minutes to complete.
I'm glad I have some preset that can use this setting without waiting.
