### ISSUE TITLE
Languages: Scala sbt and sbt-extras (Windows)

### ISSUE THREAD

**Issue by davidstaheli** [microsoft/azure-pipelines-image-generation#496]
Languages: Scala sbt and sbt-extras (Windows)

**Comment by tomvo12** [comment]
We also need sbt capable build agents to support our big data projects. Any idea, when this would be available?

**Comment by DavidStaheli** [comment]
Hi @tomvo12.  With the upcoming holidays it might not be until January.  Will that disrupt your plans?  Can you get by with installing it at the beginning of your builds until then?
```
brew install sbt
```
Or:
```
choco install sbt
```

**Comment by tomvo12** [comment]
Hi @DavidStaheli .
Thanks for the reply. If sbt would be available in the January 2019 release all is fine for us.

**Comment by dkmiller** [comment]
Currently, only way I know of to run SBT in the default agents is by installing it on the fly, either via brew or chocolatey on a "physical" agent, or via downloading a Docker container containing SBT. Having a simple build task which wraps SBT would make things _much_ easier.

**Comment by fergalsweeney** [comment]
We are looking to move to Azure Devops to build and deploy Scala app to AWS..I wish the hosted build servers supported SBT natively

**Comment by BlackTurtle123** [comment]
I also want to buil Scala apps on Azure

**Comment by quintindk** [comment]
I too would like a SBT build option in the hosted agents... Maybe someone has a how too with Docker as mentioned by @dkmiller

> Currently, only way I know of to run SBT in the default agents is by installing it on the fly, either via brew or chocolatey on a "physical" agent, or via downloading a Docker container containing SBT. Having a simple build task which wraps SBT would make things _much_ easier.

**Comment by er1c** [comment]
🙏

**Comment by er1c** [comment]
I took a stab at this via the PR: https://github.com/microsoft/azure-pipelines-image-generation/pull/1255 - happy to have other eyeballs on it :)

**Comment by jacwalte** [comment]
@er1c Looks like your PR was merged - any documentation on use?

**Comment by er1c** [comment]
@jacwalte honestly, I have no idea lol, this was my "first step" into the project.  Need to figure out how the old sbt was used.


@microsoft this should be resolved as "fixed"

**Comment by er1c** [comment]
@jacwalte  these worked for me:

```yaml
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- master
pool:
  vmImage: 'ubuntu-latest'
steps:
- script: sbt clean
  displayName: 'Running $ sbt clean'
- script: sbt update
  displayName: 'Running $ sbt update'
- script: sbt compile
  displayName: 'Running $ sbt compile'
- script: sbt test
  displayName: 'Running $ sbt test'
```
