### ISSUE TITLE
Hosted Ubuntu / DownloadPipelineArtifacts stalls at 33% until timeout

### ISSUE THREAD

**Issue by oafx** [Microsoft/azure-pipelines-image-generation#610]
## Description

Hi, I was directed here via the twitter `@AzureDevOps` account. I'm currently experiencing an issue with the Azure Pipeline Task `DownloadPipelineArtifact@0` on the hosted linux/hosted ubuntu agents, where the download freezes at 33% percent and keeps timing out after the default timeout of 30mins (eating our free hours..)

What I'm trying to achive is the following: 
1. Job A: Build a Node.js app/install dependencies
2. Use the Pipeline Artifacts as Cache, upload node_modules and build artifacts
3. Job B: Download the Pipeline Artifacts (here the described behavior from above happens)
4. Job B: Do Tests
... and so on

Am I doing this wrong? Do I have to do maintenance work/free up disk space on the agent or anything?

## Expected Behavior

This pipeline did finish successfully before, so I'd expect it to still do so (download artifact, run the tests, finish)

my azure pipelines.yml looks somewhat like this:
```yaml
#azure-pipelines.yml

jobs:
    # build talk
  - job: build
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
      - task: NodeTool@0
        displayName: 'Use Node 10.x'
        inputs:
          versionSpec: 10.x
      - script: |
          yarn
      - task: PublishPipelineArtifact@0
        displayName: 'Publish Pipeline Artifact: modules'
        inputs:
          artifactName: 'node_modules'
          targetPath: './node_modules'
  - job: test
    pool:
      vmImage: 'Ubuntu 16.04'
    dependsOn: build
    steps:
      - task: DownloadPipelineArtifact@0
        displayName: 'Download Pipeline Artifact'
        inputs:
          artifactName: 'node_modules'
          targetPath: './node_modules'
```

## Actual Behavior

Instead like described above, the download stalls at 33% and times out:

![image](https://user-images.githubusercontent.com/4024755/50017587-d2368600-ffcc-11e8-97fc-33d7956a0898.png)

and so on..

hope this is the right place to file this and thanks for your time
Christian
