### ISSUE TITLE
VCPKG_ROOT should point to $HOME/.vcpkg

### ISSUE THREAD

**Issue by DavidStaheli** [Microsoft/azure-pipelines-image-generation#769]
This is an issue brought up by #682:

To fix the issue we need to rename VCPKG_ROOT variable to something like VCPKG_INSTALLATION_ROOT. So VCPKG_INSTALLATION_ROOT will point to the vcpkg installation dir and VCPKG_ROOT will point to the $HOME/.vcpkg by default.

As a temporary workaround customers need to override VCPKG_ROOT to $HOME/.vcpkg in their scripts before using vcpkg.

**Comment by max-lobanov** [comment]
I am closing the issue since PR with fix was merged

**Comment by taketwo** [comment]
Is this fix supposed to be available on hosted Azure agents already? If not, any estimates of when it will be?

At the moment I don't see any vcpkg environment variables at all. Here is my config that simply prints all variables:

```yaml
jobs:
  - job: vs2017
    displayName: Windows VS2017 Build
    timeoutInMinutes: 0
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - script: set
displayName: 'Print environment variables'
```

The output can be seen here: https://dev.azure.com/u7p11/pcl/_build/results?buildId=322.
