### ISSUE TITLE
Install-VS2017 fails since last week

### ISSUE THREAD

**Issue by riezebosch** [Microsoft/azure-pipelines-image-generation#778]
```log
    vhd: Running
    vhd: Using default tag: latest
    vhd: latest: Pulling from microsoft/dotnet-framework
    vhd: 3889bb8d808b: Already exists
    vhd: b479a92ce115: Already exists
    vhd: 9b1f172384ea: Already exists
    vhd: 848426354374: Already exists
    vhd: 7a39188c8674: Already exists
    vhd: 4588784ea70c: Already exists
    vhd: Digest: sha256:3c3fe0db41aa3500539a9667e0f1c2f6c2cc411bb658502bef8629f01f78b70e
    vhd: Status: Downloaded newer image for microsoft/dotnet-framework:latest
==> vhd: Provisioning with Powershell...
==> vhd: Provisioning with powershell script: C:\agent1\_work\51\s\images\win/scripts/Installers/Vs2017/Install-VS2017.ps1
    vhd: Enable short name support on Windows needed for Xamarin Android AOT, defaults appear to have been changed in Azure VMs
    vhd: Downloading Bootstrapper ...
    vhd: Starting Install ...
    vhd: Non zero exit code returned by the installation process : 1.
```

**Comment by svarcoe** [comment]
I'm also running into this error. I logged into the VM and dug into the VS installer logs. I found the following error but not sure if it's related 

```
2019-03-12T17:01:49 : Error : Error: At most one command parameter can be specified
    at CommandLineErrorHandler.emit (C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\main\StubMain.js:4:652189)
    at CommandLineErrorHandler.emitError (C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\main\StubMain.js:4:651755)
    at CommandLineParser.extractAndNormalizeCommand (C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\main\StubMain.js:4:273082)
    at CommandLineParser.parse (C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\main\StubMain.js:4:269021)
    at Object.<anonymous> (C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\main\StubMain.js:4:675902)
    at __webpack_require__ (C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\main\StubMain.js:4:128)
    at Object.defineProperty.value (C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\main\StubMain.js:4:283293)
    at __webpack_require__ (C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\main\StubMain.js:4:128)
    at Object.defineProperty.value (C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\main\StubMain.js:4:743)
    at Object.<anonymous> (C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\main\StubMain.js:4:791)
```

**Comment by austin-jensen** [comment]
@riezebosch Please provide more information, is this occurring on your private agents or on one of the hosted pools? If this is on your private agents, which commit were you using?

**Comment by riezebosch** [comment]
fd33ac5, running on a private agent.

**Comment by riezebosch** [comment]
It now fails here:
```
   vhd: Installing the following packages:
    vhd: openssl.light
    vhd: By installing you accept licenses for the packages.
    vhd: Progress: Downloading OpenSSL.Light 1.1.1.20181020... 100%
    vhd:
    vhd: vcredist140 v14.16.27027.1 [Approved]
    vhd: vcredist140 package files install completed. Performing other installation steps.
    vhd: File appears to be downloaded already. Verifying with package checksum to determine if it needs to be redownloaded.
    vhd: Hashes match.
    vhd: Hashes match.
    vhd: Installing vcredist140-x86...
    vhd: WARNING: This MSI requires uninstall prior to installing a different version. Please ask the package maintainer(s) to add a check in the chocolateyInstall.ps1 script and uninstall if the software is installed. This is most likely an issue with the 'vcredist140' package and not with Chocolatey itself. Please follow up with the package maintainer(s) directly.
    vhd: ERROR: Running ["C:\Users\packer\AppData\Local\Temp\chocolatey\vcredist140\14.16.27027.1\vc_redist.x86.exe" /quiet /norestart ] was not successful. Exit code was '1638'. Exit code indicates the following: This MSI requires uninstall prior to installing a different version. Please ask the package maintainer(s) to add a check in the chocolateyInstall.ps1 script and uninstall if the software is installed. This is most likely an issue with the 'vcredist140' package and not with Chocolatey itself. Please follow up with the package maintainer(s) directly..
    vhd: The install of vcredist140 was NOT successful.
    vhd: Error while running 'C:\ProgramData\chocolatey\lib\vcredist140\tools\chocolateyInstall.ps1'.
    vhd:  See log for details.
    vhd:
    vhd: OpenSSL.Light v1.1.1.20181020 [Approved]
    vhd: openssl.light package files install completed. Performing other installation steps.
    vhd: Installing 64-bit OpenSSL.Light...
    vhd: OpenSSL.Light has been installed.
    vhd: Installed to 'C:\Program Files\OpenSSL'
    vhd: PATH environment variable does not have C:\Program Files\OpenSSL\bin in it. Adding...
    vhd:   openssl.light can be automatically uninstalled.
    vhd: Environment Vars (like PATH) have changed. Close/reopen your shell to
    vhd:  see the changes (or in powershell/cmd.exe just type `refreshenv`).
    vhd:  The install of openssl.light was successful.
    vhd:   Software installed to 'C:\Program Files\OpenSSL\'
    vhd:
    vhd: Chocolatey installed 1/2 packages. 1 packages failed.
    vhd:  See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
    vhd:
    vhd: Failures
    vhd:  - vcredist140 (exited 1638) - Error while running 'C:\ProgramData\chocolatey\lib\vcredist140\tools\chocolateyInstall.ps1'.
    vhd:  See log for details.
```

c92b68e
