### ISSUE TITLE
Container Jobs failing with min Docker version

### ISSUE THREAD

**Issue by lenisha** [Microsoft/azure-pipelines-image-generation#794]
**Describe the bug**
Trying to run Container jobs on Hosted Ubuntu 16.04 agent fails during initializeContainers step

**Expected behavior**
Container jobs run

**Actual behavior
1) Setup YAML Build with Container job
```
resources:
  containers:
  - container: nodejs
    image: node:8.15-jessie

jobs:
- job: RunNodeBuild
  container: nodejs
  pool:
    vmImage: 'Ubuntu 16.04'

  steps:
    - script: 
        npm install 
      displayName: 'Run npm install'
```

2) Error
```
##[section]Starting: Initialize containers
##[command]/usr/local/bin/docker version --format '{{.Server.Version}}'
'3.0.4'
Docker daemon version: '3.0.4'
##[command]/usr/local/bin/docker version --format '{{.Client.Version}}'
'17.12.0-ce'
Docker client version: '17.12.0-ce'
##[error]Min required docker server version is '17.12', your docker ('/usr/local/bin/docker') server version is '3.0.4'
##[section]Finishing: Initialize containers
```

**Image impacted**
ubuntu
