### ISSUE TITLE
DEP0600 error when VS Test tries to deploy my UAP unit tests app

### ISSUE THREAD

**Issue by nathan-alden-hp** [Microsoft/azure-pipelines-image-generation#818]
**Describe the bug**
I'm using the new `windows-2019` image. I'm attempting to run unit tests through a UAP unit tests project (which is really an app, but I digress). I am seeing this error in my output:
```
vstest.console.exe 
"d:\a\1\s\test\ClassLibrary.UnitTests\bin\x64\Release\ClassLibrary.UnitTests.build.appxrecipe"
/Settings:"d:\a\1\s\test\uap-10.0-x64.runsettings"
/logger:"trx"
/TestAdapterPath:"d:\a\1\s"
Starting test execution, please wait...
Attempting to deploy to target 'Local Machine'.
DEP0600: Deployment failed. Object reference not set to an instance of an object.
```
These tests run just fine locally with the same `.runsettings` file. I'm pretty sure these tests also worked a couple of weeks ago when I originally wrote the pipeline. Given the vagueness of the error, I'm not sure how to proceed other than by reporting this as a bug.

**Expected behavior**
VS Test runs the unit test project as expected.

**Actual behavior**
```
DEP0600: Deployment failed. Object reference not set to an instance of an object.
```
I can't easily give steps to reproduce since this is running proprietary source code. However, here is the YAML template I use for this step:
```
parameters:
  msbuildConfiguration: Release
  platform: x64
  runInParallel: true
  testRecipes: test/*.UnitTests/bin/x64/Release/*.UnitTests.build.appxrecipe
  vsTestVersion: latest
  runSettingsFile: test/uap-10.0-x64.runsettings

steps:
- task: VSTest@2
  displayName: Run tests
  inputs:
    testSelector: testAssemblies
    testAssemblyVer2: '${{ parameters.testRecipes }}'
    vsTestVersion: '${{ parameters.vsTestVersion }}'
    configuration: '${{ parameters.msbuildConfiguration }}'
    runSettingsFile: '${{ parameters.runSettingsFile }}'
    uiTests: true
```
`test/uap-10.0-x64.runsettings` file:
```
<?xml version="1.0" encoding="utf-8"?>
<RunSettings>
  <RunConfiguration>
    <TargetFrameworkVersion>FrameworkUap10</TargetFrameworkVersion>
    <TargetPlatform>x64</TargetPlatform>
  </RunConfiguration>
</RunSettings>
```

**Image impacted**
`windows-2019`
