### ISSUE TITLE
Docker login from PowerShell

### ISSUE THREAD

**Issue by duracellko** [Microsoft/azure-pipelines-image-generation#829]
**Describe the bug**

Authentication fails when passing password to `docker login` via pipe in PowerShell on Windows.

**Expected behavior**
PowerShell and Docker login behave same on Windows and Ubuntu.

**Actual behavior**

I have following build task:
```yaml
  - task: PowerShell@2
    displayName: 'Build Docker image'
    inputs:
      targetType: inline
      script: |
        $registryName = 'xxx.azurecr.io'
        $registryUser = $env:REGISTRY_SERVICEPRINCIPAL_ID
        $registryPassword = $env:REGISTRY_SERVICEPRINCIPAL_PASSWORD
        
        Write-Host "Login to $registryName as $registryUser"
        $registryPassword | & docker login --username $registryUser --password-stdin $registryName
```

The build task fails with following error on `windows-2019` and `vs2017-win2016`:
```
##[error]Error response from daemon: Get https://ErniToolchainB5011.azurecr.io/v2/: unauthorized: authentication required
```

The same build passes successfully on `ubuntu-16.04`. Also running same script locally on Windows 10 with PowerShell 5.1.17763.316 and Docker 18.09.2 works fine.

At first I thought I had wrong configuration of variables. I tried several combinations like secret variables, non-secret variables, even setting values directly in the PowerShell script.

**Workaround**

I found out that passing password as parameter and not via pipe works. Just command must be executed with SilentlyContinue, because of warning that is not secure.

```powershell
$argumentList = @('login', '--username', $registryUser, '--password', $registryPassword, $registryName)
$process = Start-Process -FilePath 'docker.exe' -ArgumentList $argumentList -PassThru -Wait -NoNewWindow -ErrorAction SilentlyContinue
    if (($null -eq $process) -or ($process.ExitCode -ne 0)) {
        throw "Login to $registryName failed."
    }
```

**Image impacted**

- windows-2019
- vs2017-win2016

**Comment by vtbassmatt** [comment]
That's unexpected. Does it work differently if you use this syntax:
```yaml
- pwsh: |
    <your script>
  displayName: 'Build Docker image'
```

**Comment by duracellko** [comment]
It seems it works in PowerShell Core, just not in PowerShell.

Both scripts work:

```yaml
- pwsh: |
    <your script>
  displayName: 'Build Docker image'
```

and also task with pwsh set to true.

```yaml
- task: PowerShell@2
    displayName: 'Build Docker image'
    pwsh: true
    inputs:
      targetType: inline
      script: |
        $registryName = 'xxx.azurecr.io'
        $registryUser = $env:REGISTRY_SERVICEPRINCIPAL_ID
        $registryPassword = $env:REGISTRY_PASSWORD
        
        Write-Host "Login to $registryName as $registryUser"
        $registryPassword | & docker login --username $registryUser --password-stdin $registryName
    env:
      REGISTRY_PASSWORD: $(Registry.ServicePrincipal.Password)
```
