### ISSUE TITLE
Win-2019 warning turns to error (and is treated like error) for python Commands in Powershell 

### ISSUE THREAD

**Issue by gauravsaralMs** [microsoft/azure-pipelines-image-generation#890]
**Describe the bug**
Warning from python commands in powershell are treated as error in Win-2019 image where as they are treated as warning in Win-2017 and Ubuntu image.
So basically same command works differently across images

**Expected behavior**
Same command should work in same manner across images

**Actual behavior**

**Image impacted**
'windows-2019'

Attaching the yaml 

```yaml
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:

- job: 'Run_on_VS2019'
  pool:
    vmImage: 'windows-2019'

  steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: 'pip install knack'

- job: 'Run_on_VS2017'
  pool:
    vmImage: 'vs2017-win2016'

  steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: 'pip install knack'

- job: 'Run_on_Ubuntu'
  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: 'pip install knack'
```
