### ISSUE TITLE
[Performance] 10 Second Delay on Powershell Core First Task Start for Windows Agents

### ISSUE THREAD

**Issue by JustinGrote** [microsoft/azure-pipelines-image-generation#981]
**Describe the bug**
On the first invocation of a pwsh: task, it takes 10-20 additional seconds to run. This doesn't happen on subsequent runs, indicating some sort of initialization that may be occuring that should be "pre-cached" in the build. This could be as simple as running pwsh once before packing the agent.

Confirmed Present on Windows Agent hosts, but doesn't happen for Linux hosts.

**Expected behavior**
~1 second time for first pwsh: invocation

**Actual behavior**
10-20 second time for first run, fine thereafter

```yaml
jobs:
  - job: 
    pool:
      vmImage: vs2017-win2016
    steps:
      - powershell: |
          Write-Output "Test"
        displayName: This is fast
      - powershell: |
          Write-Output "Test"
        displayName: This and all subsequent are also fast
      - pwsh: |
          Write-Output "Test"
        displayName: This one takes 10-20 seconds for some reason
      - pwsh: |
          Write-Output "Test"
        displayName: This and all others now go fast
```
![image](https://user-images.githubusercontent.com/15258962/58656274-d29fb080-82d0-11e9-89f4-3e141a146cd7.png)

**Image impacted**
All Windows with pwsh
