### ISSUE TITLE
[windows] [rust] cargo: no default toolchain configured

### ISSUE THREAD

**Issue by asottile** [microsoft/azure-pipelines-image-generation#988]
**Describe the bug**

`cargo` is unable to find the installed rust toolchain without specific environment variables

**Expected behavior**

I expect `cargo` to be able to find the toolchain.  When installed with rustup manually, `cargo` is able to find the installed `rustc`.

**Actual behavior**
A description with steps to reproduce the issue.

Using this configuration:

```yaml
trigger:
  branches:
    include: [master, test-me-*]
  tags:
    include: ['*']

jobs:
- job: demo
  pool:
    vmImage: vs2017-win2016
  steps:
    - bash: |
        set -euxo pipefail
        mkdir -p foo
        env -i "$(which cargo)" install --bins --root "$PWD/foo" shellharden
```

Output:

```
##[section]Starting: Bash
==============================================================================
Task         : Bash
Description  : Run a Bash script on macOS, Linux, or Windows
Version      : 3.148.2
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613738)
==============================================================================
Generating script.
[command]"C:\Program Files\Git\bin\bash.exe" --noprofile --norc -c pwd
/d/a/_temp
========================== Starting Command Output ===========================
[command]"C:\Program Files\Git\bin\bash.exe" --noprofile --norc /d/a/_temp/21633a12-9b2a-4d92-b78e-9946d5be1c00.sh
+ mkdir -p foo
++ which cargo
+ env -i '/c/Program Files/Rust/.cargo/bin/cargo' install --bins --root /d/a/1/s/foo shellharden
error: no default toolchain configured
##[error]Bash exited with code '1'.
##[section]Finishing: Bash
```

Link: https://asottile.visualstudio.com/asottile/_build/results?buildId=724

**Image impacted**

I've only tried this on vs2017-win2016 -- my org hasn't been opted into the ubuntu rust-enabled images yet
