### ISSUE TITLE
[windows] [python] py launcher misconfigured for 3.7

### ISSUE THREAD

**Issue by asottile** [microsoft/azure-pipelines-image-generation#989]
**Describe the bug**

After `UsePythonVersion` I should be able to `py -3.7`, however it is not succeeding.  It used to work on the previous image builds (when 3.7.2 was installed) but not any more now that 3.7.3 is installed.

**Expected behavior**

I expect `py -3.7` to function

**Actual behavior**

```yaml
trigger:
  branches:
    include: [master, test-me-*]
  tags:
    include: ['*']

jobs:
- job:
  pool:
    vmImage: vs2017-win2016
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
  - bash: |
      set -euxo pipefail
      py -3.7 -c 'import sys; print(sys.executable)'
```

Output

```
##[section]Starting: Bash
==============================================================================
Task         : Bash
Description  : Run a Bash script on macOS, Linux, or Windows
Version      : 3.148.2
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613738)
==============================================================================
Generating script.
[command]"C:\Program Files\Git\bin\bash.exe" --noprofile --norc -c pwd
/d/a/_temp
========================== Starting Command Output ===========================
[command]"C:\Program Files\Git\bin\bash.exe" --noprofile --norc /d/a/_temp/cf6c9d04-02a9-4f5d-8dcf-b5f4addf10ca.sh
+ py -3.7 -c 'import sys; print(sys.executable)'
Requested Python version (3.7) not installed
##[error]Bash exited with code '103'.
##[section]Finishing: Bash
```

link: https://asottile.visualstudio.com/asottile/_build/results?buildId=731

**Image impacted**

Only tested on the windows image

**Comment by asottile** [comment]
CC @gaborbernat since I assume you'll hit this on either tox / virtualenv

**Comment by gaborbernat** [comment]
nope, tox no longer uses py underneath, uses either directly pep-514 or fallbacks to other sources. I don't expect tox users to notice this.

**Comment by asottile** [comment]
@gaborbernat bad news, the registry approach also suffers: https://asottile.visualstudio.com/asottile/_build/results?buildId=734

```yaml
trigger:
  branches:
    include: [master, test-me-*]
  tags:
    include: ['*']

jobs:
- job:
  pool:
    vmImage: vs2017-win2016
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
  - bash: pip install tox
  - bash: tox -e py37 --notest
```
